services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn core.wsgi:application"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
